//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ClientsCommunicationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultOfServerClienta_PaS5gWf", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial struct OperationResultOfServerClienta_PaS5gWf : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ClientsCommunicationService.ServerClient ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Client.ClientsCommunicationService.ServerFault> ServerFaultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ClientsCommunicationService.ServerClient Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Client.ClientsCommunicationService.ServerFault> ServerFault {
            get {
                return this.ServerFaultField;
            }
            set {
                if ((this.ServerFaultField.Equals(value) != true)) {
                    this.ServerFaultField = value;
                    this.RaisePropertyChanged("ServerFault");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerClient", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class ServerClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Net.IPEndPoint IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ClientsCommunicationService.Session[] SessionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Net.IPEndPoint IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ClientsCommunicationService.Session[] Sessions {
            get {
                return this.SessionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionsField, value) != true)) {
                    this.SessionsField = value;
                    this.RaisePropertyChanged("Sessions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    public enum ServerFault : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArgumentNull_Exception = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerClient_NicknameOccupied_Exception = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerClient_IPAddressOccupied_Exception = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Session_NameOccupied_Exception = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongPassword_Exception = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ClientsCommunicationService.ServerClient[] ClientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ClientsCommunicationService.ServerClient CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPasswordRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ClientsCommunicationService.ServerClient[] Clients {
            get {
                return this.ClientsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientsField, value) != true)) {
                    this.ClientsField = value;
                    this.RaisePropertyChanged("Clients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ClientsCommunicationService.ServerClient Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPasswordRequired {
            get {
                return this.IsPasswordRequiredField;
            }
            set {
                if ((this.IsPasswordRequiredField.Equals(value) != true)) {
                    this.IsPasswordRequiredField = value;
                    this.RaisePropertyChanged("IsPasswordRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionName {
            get {
                return this.SessionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionNameField, value) != true)) {
                    this.SessionNameField = value;
                    this.RaisePropertyChanged("SessionName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultOfSessiona_PaS5gWf", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial struct OperationResultOfSessiona_PaS5gWf : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ClientsCommunicationService.Session ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Client.ClientsCommunicationService.ServerFault> ServerFaultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ClientsCommunicationService.Session Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Client.ClientsCommunicationService.ServerFault> ServerFault {
            get {
                return this.ServerFaultField;
            }
            set {
                if ((this.ServerFaultField.Equals(value) != true)) {
                    this.ServerFaultField = value;
                    this.RaisePropertyChanged("ServerFault");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultOfArrayOfSessiona_PaS5gWf", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial struct OperationResultOfArrayOfSessiona_PaS5gWf : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ClientsCommunicationService.Session[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Client.ClientsCommunicationService.ServerFault> ServerFaultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.ClientsCommunicationService.Session[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Client.ClientsCommunicationService.ServerFault> ServerFault {
            get {
                return this.ServerFaultField;
            }
            set {
                if ((this.ServerFaultField.Equals(value) != true)) {
                    this.ServerFaultField = value;
                    this.RaisePropertyChanged("ServerFault");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionDeletionCause", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.SerializableAttribute()]
    public partial class SessionDeletionCause : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientsCommunicationService.IClientsCommunicationService", CallbackContract=typeof(Client.ClientsCommunicationService.IClientsCommunicationServiceCallback))]
    public interface IClientsCommunicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/Connect", ReplyAction="http://tempuri.org/IClientsCommunicationService/ConnectResponse")]
        Client.ClientsCommunicationService.OperationResultOfServerClienta_PaS5gWf Connect(System.Net.IPEndPoint IPAddress, string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/Connect", ReplyAction="http://tempuri.org/IClientsCommunicationService/ConnectResponse")]
        System.Threading.Tasks.Task<Client.ClientsCommunicationService.OperationResultOfServerClienta_PaS5gWf> ConnectAsync(System.Net.IPEndPoint IPAddress, string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/UpdateClientIPAddress", ReplyAction="http://tempuri.org/IClientsCommunicationService/UpdateClientIPAddressResponse")]
        System.Nullable<Client.ClientsCommunicationService.ServerFault> UpdateClientIPAddress(Client.ClientsCommunicationService.ServerClient serverClient, System.Net.IPEndPoint newIPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/UpdateClientIPAddress", ReplyAction="http://tempuri.org/IClientsCommunicationService/UpdateClientIPAddressResponse")]
        System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> UpdateClientIPAddressAsync(Client.ClientsCommunicationService.ServerClient serverClient, System.Net.IPEndPoint newIPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/ChangeNickName", ReplyAction="http://tempuri.org/IClientsCommunicationService/ChangeNickNameResponse")]
        System.Nullable<Client.ClientsCommunicationService.ServerFault> ChangeNickName(Client.ClientsCommunicationService.ServerClient serverClient, string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/ChangeNickName", ReplyAction="http://tempuri.org/IClientsCommunicationService/ChangeNickNameResponse")]
        System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> ChangeNickNameAsync(Client.ClientsCommunicationService.ServerClient serverClient, string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/Disconnect", ReplyAction="http://tempuri.org/IClientsCommunicationService/DisconnectResponse")]
        System.Nullable<Client.ClientsCommunicationService.ServerFault> Disconnect(Client.ClientsCommunicationService.ServerClient serverClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/Disconnect", ReplyAction="http://tempuri.org/IClientsCommunicationService/DisconnectResponse")]
        System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> DisconnectAsync(Client.ClientsCommunicationService.ServerClient serverClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/CreateSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/CreateSessionResponse")]
        Client.ClientsCommunicationService.OperationResultOfSessiona_PaS5gWf CreateSession(Client.ClientsCommunicationService.ServerClient serverClient, string sessionName, string sessionPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/CreateSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/CreateSessionResponse")]
        System.Threading.Tasks.Task<Client.ClientsCommunicationService.OperationResultOfSessiona_PaS5gWf> CreateSessionAsync(Client.ClientsCommunicationService.ServerClient serverClient, string sessionName, string sessionPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/RenameSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/RenameSessionResponse")]
        System.Nullable<Client.ClientsCommunicationService.ServerFault> RenameSession(Client.ClientsCommunicationService.Session session, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/RenameSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/RenameSessionResponse")]
        System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> RenameSessionAsync(Client.ClientsCommunicationService.Session session, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/ChangeSessionPassword", ReplyAction="http://tempuri.org/IClientsCommunicationService/ChangeSessionPasswordResponse")]
        System.Nullable<Client.ClientsCommunicationService.ServerFault> ChangeSessionPassword(Client.ClientsCommunicationService.Session session, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/ChangeSessionPassword", ReplyAction="http://tempuri.org/IClientsCommunicationService/ChangeSessionPasswordResponse")]
        System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> ChangeSessionPasswordAsync(Client.ClientsCommunicationService.Session session, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/GetSessionsList", ReplyAction="http://tempuri.org/IClientsCommunicationService/GetSessionsListResponse")]
        Client.ClientsCommunicationService.OperationResultOfArrayOfSessiona_PaS5gWf GetSessionsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/GetSessionsList", ReplyAction="http://tempuri.org/IClientsCommunicationService/GetSessionsListResponse")]
        System.Threading.Tasks.Task<Client.ClientsCommunicationService.OperationResultOfArrayOfSessiona_PaS5gWf> GetSessionsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/DeleteSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/DeleteSessionResponse")]
        System.Nullable<Client.ClientsCommunicationService.ServerFault> DeleteSession(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.SessionDeletionCause deletionCause);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/DeleteSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/DeleteSessionResponse")]
        System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> DeleteSessionAsync(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.SessionDeletionCause deletionCause);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/DisconnectFromSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/DisconnectFromSessionResponse")]
        System.Nullable<Client.ClientsCommunicationService.ServerFault> DisconnectFromSession(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient serverClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/DisconnectFromSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/DisconnectFromSessionResponse")]
        System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> DisconnectFromSessionAsync(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient serverClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/JoinSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/JoinSessionResponse")]
        System.Nullable<Client.ClientsCommunicationService.ServerFault> JoinSession(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient serverClient, string sessionPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/JoinSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/JoinSessionResponse")]
        System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> JoinSessionAsync(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient serverClient, string sessionPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientsCommunicationServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/NewSessionCreated", ReplyAction="http://tempuri.org/IClientsCommunicationService/NewSessionCreatedResponse")]
        void NewSessionCreated(Client.ClientsCommunicationService.Session newSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/ClientJoinedSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/ClientJoinedSessionResponse")]
        void ClientJoinedSession(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient joinedClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/ClientLeftSession", ReplyAction="http://tempuri.org/IClientsCommunicationService/ClientLeftSessionResponse")]
        void ClientLeftSession(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient clientLeft);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/SessionNameChanged", ReplyAction="http://tempuri.org/IClientsCommunicationService/SessionNameChangedResponse")]
        void SessionNameChanged(Client.ClientsCommunicationService.Session session, string sessionOldName, string sessionNewName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/SessionPasswordChanged", ReplyAction="http://tempuri.org/IClientsCommunicationService/SessionPasswordChangedResponse")]
        void SessionPasswordChanged(Client.ClientsCommunicationService.Session session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/SessionClientNickNameChanged", ReplyAction="http://tempuri.org/IClientsCommunicationService/SessionClientNickNameChangedRespo" +
            "nse")]
        void SessionClientNickNameChanged(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient serverClient, string clientOldNickName, string clientNewNickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/SessionClientIPAddressChanged", ReplyAction="http://tempuri.org/IClientsCommunicationService/SessionClientIPAddressChangedResp" +
            "onse")]
        void SessionClientIPAddressChanged(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient serverClient, System.Net.IPEndPoint clientOldIPAddress, System.Net.IPEndPoint clientNewIPAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/SessionDeleted", ReplyAction="http://tempuri.org/IClientsCommunicationService/SessionDeletedResponse")]
        void SessionDeleted(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.SessionDeletionCause sessionDeletionCause);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientsCommunicationService/ServerShutDownNoticeReceive", ReplyAction="http://tempuri.org/IClientsCommunicationService/ServerShutDownNoticeReceiveRespon" +
            "se")]
        void ServerShutDownNoticeReceive(long millisecondsBeforeShutDown);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientsCommunicationServiceChannel : Client.ClientsCommunicationService.IClientsCommunicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientsCommunicationServiceClient : System.ServiceModel.DuplexClientBase<Client.ClientsCommunicationService.IClientsCommunicationService>, Client.ClientsCommunicationService.IClientsCommunicationService {
        
        public ClientsCommunicationServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ClientsCommunicationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ClientsCommunicationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ClientsCommunicationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ClientsCommunicationServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Client.ClientsCommunicationService.OperationResultOfServerClienta_PaS5gWf Connect(System.Net.IPEndPoint IPAddress, string nickName) {
            return base.Channel.Connect(IPAddress, nickName);
        }
        
        public System.Threading.Tasks.Task<Client.ClientsCommunicationService.OperationResultOfServerClienta_PaS5gWf> ConnectAsync(System.Net.IPEndPoint IPAddress, string nickName) {
            return base.Channel.ConnectAsync(IPAddress, nickName);
        }
        
        public System.Nullable<Client.ClientsCommunicationService.ServerFault> UpdateClientIPAddress(Client.ClientsCommunicationService.ServerClient serverClient, System.Net.IPEndPoint newIPAddress) {
            return base.Channel.UpdateClientIPAddress(serverClient, newIPAddress);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> UpdateClientIPAddressAsync(Client.ClientsCommunicationService.ServerClient serverClient, System.Net.IPEndPoint newIPAddress) {
            return base.Channel.UpdateClientIPAddressAsync(serverClient, newIPAddress);
        }
        
        public System.Nullable<Client.ClientsCommunicationService.ServerFault> ChangeNickName(Client.ClientsCommunicationService.ServerClient serverClient, string nickName) {
            return base.Channel.ChangeNickName(serverClient, nickName);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> ChangeNickNameAsync(Client.ClientsCommunicationService.ServerClient serverClient, string nickName) {
            return base.Channel.ChangeNickNameAsync(serverClient, nickName);
        }
        
        public System.Nullable<Client.ClientsCommunicationService.ServerFault> Disconnect(Client.ClientsCommunicationService.ServerClient serverClient) {
            return base.Channel.Disconnect(serverClient);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> DisconnectAsync(Client.ClientsCommunicationService.ServerClient serverClient) {
            return base.Channel.DisconnectAsync(serverClient);
        }
        
        public Client.ClientsCommunicationService.OperationResultOfSessiona_PaS5gWf CreateSession(Client.ClientsCommunicationService.ServerClient serverClient, string sessionName, string sessionPassword) {
            return base.Channel.CreateSession(serverClient, sessionName, sessionPassword);
        }
        
        public System.Threading.Tasks.Task<Client.ClientsCommunicationService.OperationResultOfSessiona_PaS5gWf> CreateSessionAsync(Client.ClientsCommunicationService.ServerClient serverClient, string sessionName, string sessionPassword) {
            return base.Channel.CreateSessionAsync(serverClient, sessionName, sessionPassword);
        }
        
        public System.Nullable<Client.ClientsCommunicationService.ServerFault> RenameSession(Client.ClientsCommunicationService.Session session, string newName) {
            return base.Channel.RenameSession(session, newName);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> RenameSessionAsync(Client.ClientsCommunicationService.Session session, string newName) {
            return base.Channel.RenameSessionAsync(session, newName);
        }
        
        public System.Nullable<Client.ClientsCommunicationService.ServerFault> ChangeSessionPassword(Client.ClientsCommunicationService.Session session, string newPassword) {
            return base.Channel.ChangeSessionPassword(session, newPassword);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> ChangeSessionPasswordAsync(Client.ClientsCommunicationService.Session session, string newPassword) {
            return base.Channel.ChangeSessionPasswordAsync(session, newPassword);
        }
        
        public Client.ClientsCommunicationService.OperationResultOfArrayOfSessiona_PaS5gWf GetSessionsList() {
            return base.Channel.GetSessionsList();
        }
        
        public System.Threading.Tasks.Task<Client.ClientsCommunicationService.OperationResultOfArrayOfSessiona_PaS5gWf> GetSessionsListAsync() {
            return base.Channel.GetSessionsListAsync();
        }
        
        public System.Nullable<Client.ClientsCommunicationService.ServerFault> DeleteSession(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.SessionDeletionCause deletionCause) {
            return base.Channel.DeleteSession(session, deletionCause);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> DeleteSessionAsync(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.SessionDeletionCause deletionCause) {
            return base.Channel.DeleteSessionAsync(session, deletionCause);
        }
        
        public System.Nullable<Client.ClientsCommunicationService.ServerFault> DisconnectFromSession(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient serverClient) {
            return base.Channel.DisconnectFromSession(session, serverClient);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> DisconnectFromSessionAsync(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient serverClient) {
            return base.Channel.DisconnectFromSessionAsync(session, serverClient);
        }
        
        public System.Nullable<Client.ClientsCommunicationService.ServerFault> JoinSession(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient serverClient, string sessionPassword) {
            return base.Channel.JoinSession(session, serverClient, sessionPassword);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<Client.ClientsCommunicationService.ServerFault>> JoinSessionAsync(Client.ClientsCommunicationService.Session session, Client.ClientsCommunicationService.ServerClient serverClient, string sessionPassword) {
            return base.Channel.JoinSessionAsync(session, serverClient, sessionPassword);
        }
    }
}
